// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Box1: typeof import('./src/components/message/box1.vue')['default']
    Box2: typeof import('./src/components/message/box2.vue')['default']
    Box3: typeof import('./src/components/message/box3.vue')['default']
    Count: typeof import('./src/components/count.vue')['default']
    Counter: typeof import('./src/components/Counter.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    GmView: typeof import('./src/components/Navigate/gmView.vue')['default']
    LogView: typeof import('./src/components/Navigate/LogView.vue')['default']
    Manager: typeof import('./src/components/message/Manager.vue')['default']
    MapView: typeof import('./src/components/Navigate/MapView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchView: typeof import('./src/components/Navigate/SearchView.vue')['default']
  }
}

export { }
