// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Clock: typeof import('./src/components/clock.vue')['default']
    Counter: typeof import('./src/components/Counter.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    FormLogin: typeof import('./src/components/FormLogin.vue')['default']
    GmView: typeof import('./src/components/Navigate/gmView.vue')['default']
    MapView: typeof import('./src/components/Navigate/MapView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchView: typeof import('./src/components/Navigate/SearchView.vue')['default']
    Test: typeof import('./src/components/test.vue')['default']
  }
}

export { }
